### ISSUE TITLE
Handle periods in module names

### ISSUE THREAD

**Issue by pwwolf** [BlueOakJS/blueoak-server#5]
Currently using a period in a handler name will cause a problem because periods are used internally to delineate module prefixes, such as handlers be "handler.<mod name>" or middleware being "middleware.<mod name>".

It's unlikely a module will have a period in the filename, so this will be low priority.

We also need to decide how periods would be handled in the dependency injection, since JS variables cannot have periods.

**Comment by seanpk** [comment]
#resurrect: we should document this, add an error message, and close this issue

... or, if we're not going to get to it soon, close this as "won't fix" and open another with a title that is less "scary" ;-)
