### ISSUE TITLE
Swagger validation does not process the actual polymorphic model

### ISSUE THREAD

**Issue by seanpk** [BlueOakJS/blueoak-server#60]
the Swagger spec provides support of [inheritance using the `discriminator` property](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#composition-and-inheritance-polymorphism)

BlueOak Server does not process these models to validate against the actual type of the provided model.
Ideally it does.

**Comment by ryshep111** [comment]
have (untested) fix for this on my machine

**Comment by ryshep111** [comment]
Changes in fork: https://github.com/PointSource/blueoak-server/tree/polymorphic-validation%2360

**Comment by ryshep111** [comment]
moved to https://github.com/ryshep111/blueoak-server/tree/polymorphic-validation%2360
