### ISSUE TITLE
how to mock the data for swagger api

### ISSUE THREAD

**Issue by kazaff** [BlueOakJS/blueoak-server#65]
i need a tool that can mock the data for swagger api spec, do anybody knows how? maybe a third-part middleware or handler?

**Comment by seanpk** [comment]
there's nothing in BlueOak Server to auto-generate mock data ... but it could help speed you up (a lot, IMO):

- drop your spec in the `swagger/` directory of a BlueOak Server project (say that you've created by following instructions in the [template](https://github.com/BlueOakJS/blueoak-server-template))
- now you can serve that spec, and even use Swagger UI to explore it by pointing to `<hostname>:3003/swagger/<base-specfilename>` (e.g. `http://localhost:3003/swagger/api-v1`)
  - yes, you don't have to implement any code to start serving your spec
  - (this is how I write my swagger spec now: YAML files, in my favorite local editor, with source control, with BOS and `nodemon`)
- start adding [handler functions](https://github.com/BlueOakJS/blueoak-server/wiki/Handlers) to the `handlers/` directory to provide the mock service for each endpoint in the swagger spec 
- the name of the functions exported from the handler file must match the `operationId` defined in the path method in the swagger
- connect the mock implementation by adding an `x-handler` property to each path in your swagger spec with the name of the file with your mock implementation in `handlers/`
  - (you can skip this if you chose to put all your functions in a single file matching the filename of your spec, e.g. `handlers/api-v1.js` will be used by default for `swagger/api-v1.json` (or `swagger/api-v1.yaml`))
  - (I prefer to have a handler for each major API resource, e.g. for the petstore example, I'd have one handler for each of `pet`, `store`, and `user`)
- to help with serving valid mock data, turn on [response model validation](https://github.com/BlueOakJS/blueoak-server/wiki/Handlers#swagger-model-validation) while you're creating mock data to have BOS validate the data in the response against the model in the swagger

let me know if you give it a shot how it goes, how it helps (or doesn't), and if you have more questions
