### ISSUE TITLE
config wiki looks pretty bare

### ISSUE THREAD

**Issue by ryshep111** [BlueOakJS/blueoak-server#70]
First glance at the config wiki looks to me like there is a lot missing. I think there is information about the config scattered across the other parts of the wiki that would also be good to have in here. There may also be parts of the config that are missing from the wiki entirely. Need to investigate further.

**Comment by ryshep111** [comment]
Added links to other parts of the wiki that contain information about config

**Comment by seanpk** [comment]
@ryshep111 do you think your changes have resolved this particular concern?

**Comment by ryshep111** [comment]
actually no, I still need to at a minimum add docs for built in middleware config

**Comment by ryshep111** [comment]
Ok so the built in middleware docs were already there for the most part. I just added a section for multer.
