### ISSUE TITLE
Provide a standard BlueOak namespace where applicable

### ISSUE THREAD

**Issue by gconsidine** [BlueOakJS/blueoak-server#74]
There are cases where BlueOak and/or external BlueOak packages will introduce custom fields to Swagger, add data to the Express-based `request` object, and so on.  In those cases, it'd be nice to have a standard namespace to reduce the risk of collision and to spot something BlueOak-specific at a glance.  

For example:
- In middleware/handlers: `req.bos.user` instead of `req.user`
- In Swagger, `x-bos-security` instead of `x-security`

**Comment by seanpk** [comment]
I think `req.user` is an [express.js convention](http://expressjs.com/en/4x/api.html#app.param) for adding the context of the authorized user to the request.
It is [where passport puts that info](http://passportjs.org/docs/authenticate).
There is currently no code in the project that sets `req.user` anyway.

I do think it makes sense to support, and prefer going forward, the `x-bos-` prefix for Swagger spec extensions over the plain `x-`that is in use today. (Of course, the current naming will keep working for the foreseeable future.
i.e.:
`'x-handler'` --> `'x-bos-handler'`
`'x-middleware'` --> `'x-bos-middleware'`
