### ISSUE TITLE
Swagger handling of default and required fields only works with strings

### ISSUE THREAD

**Issue by jeff-lee-ps** [BlueOakJS/blueoak-server#75]
I have a query parameter that is a boolean and one that is an integer type.  If I set the default attribute to the native true or a non-zero number, then it works as expected and my runtime code receives that value.  If I set the default attribute to native false or 0, then the runtime code instead receives undefined as the value.

I can only get a non-truthy value to work if it is provided as a string...

```
- name: intField
          in: query
          description: ...
          required: false
          type: integer
          format: int32
          default: '0'
- name: booleanField
          in: query
          description: ...
          required: false
          type: boolean
          default: 'false'
```
The problem is the code has two spots I saw like this:
```
if (parm.in === 'query') {
    if (parm.default && typeof (req.query[parm.name]) === 'undefined') {
        req.query[parm.name] = swaggerUtil.cast(parm, parm.default);
    }
}
```
Where the handling of parm.default does not work for false or 0 correctly.  In the validation code right below that, I see the same error with parm.required where a yaml definition of 'false' is going to be treated the same as required set to true.

```
if (parm.required && typeof (req.query[parm.name]) === 'undefined') {
    logger.warn('Missing query parameter "%s" for operation "%s"', parm.name, data.operationId);
```

**Comment by ryshep111** [comment]
The required property should always be type boolean, so that part is fine. [PR](../pull/76) submitted for default values fix.
