### ISSUE TITLE
nodemon restarting endlessly in swagger example

### ISSUE THREAD

**Issue by karpovalex** [BlueOakJS/blueoak-server#78]
nodejs v.6.8.0
npm v3.10.8

alex@alex-GL62-6QD:~/bo/blueoak-server/examples/swagger$ nodemon
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.* /home/alex/bo/blueoak-server/**/*
[nodemon] starting `node index.js`
info: index.js - Starting blueoak-server v2.5.0 in development mode using Node.js v6.8.0
info: index.js - Clustering is disabled
info: monitor - Monitoring is disabled.
info: swagger - Ref compilation is enabled (true), compiling references...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] starting `node index.js`
info: index.js - Starting blueoak-server v2.5.0 in development mode using Node.js v6.8.0
info: index.js - Clustering is disabled
info: monitor - Monitoring is disabled.
info: swagger - Ref compilation is enabled (true), compiling references...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] starting `node index.js`

**Comment by ryshep111** [comment]
This is because you have ref compiler enabled, which will modify the swagger specs on server start. You can disable ref compiler, or start the server without watching for changes on .yaml or .json files.

**Comment by ryshep111** [comment]
it should not have been turned on by default though, looking into that

**Comment by seanpk** [comment]
@karpovalex - if you pull the latest from `master` this problem should disappear.

(also, since it is in example code, I don't intend to publish a new version to npm)
