### ISSUE TITLE
Programmatic logger is not found correctly

### ISSUE THREAD

**Issue by jeff-lee-ps** [BlueOakJS/blueoak-server#91]
https://github.com/BlueOakJS/blueoak-server/wiki/Logging-Service

This contains the text "Create a logger.js in your application directory with an init method." when attempting to use programmatic control of the logger; however, we could not get that to work.  We were replacing the stringify() method in the logger to get single line json output for Splunk integration.  The problem is the blueoak logger calls this:

var extLogger = require(global.__appDir + '/' + 'logger');

But that does not find the logger.js in app directory because it's working directory is something like blueoak/services (we have an explicit appDir as "./dist").  I don't know if this only fails because we have an explicit appDir or if it always fails.  We got it to work locally by changing that to use this instead:

var extLogger = require(path.resolve(global.__appDir, 'logger'));

**Comment by seanpk** [comment]
please submit a PR

**Comment by jeff-lee-ps** [comment]
PR #94 submitted

**Comment by seanpk** [comment]
Fixed in v2.9.4
