### ISSUE TITLE
Expose function for model validation to user code

### ISSUE THREAD

**Issue by seanpk** [BlueOakJS/blueoak-server#97]
The Swagger/OpenAPI model validation built-in is great for handling API requests (and responses in development).
Sometimes, however, user code wants to validate that a given object in memory conforms to the model definition. (This could be because the model has been loaded out of a database and we want to confirm it fits with the latest code before using it, probably fixing it up before we do; or other things.)

**Idea:**
- extract the body validation algorithm from `handlers/_swagger.js/validateRequestParameters/_validateParameter`, currently `line 571` on `master`, to an addressable function
- it looks like that function needs as input:
  - the spec to use
  - the model name to validate against
  - the object to validate
  - (optional) whether polymorphic validation is on (it should be by default)
- it should then return an errors report that a developer could use to figure things out programmatically (or null if there's no validation error)

**Notes:**
- there is some logging in the `_swagger` handler that will need to get moved out of the main algorithm and done only in this code
- the `validateResponseModels` function in the `_swagger` handler could/should probably make use of this new function

**Comment by dannylevenson** [comment]
@seanpk This looks good. It would be nice to provide an option for the output to be either an error report as you've already specified, or a RequestValidationError as the current code does.

**Comment by seanpk** [comment]
@dannylevenson - looking at the code, I think that the ideas are the same thing ... but we'll keep this in mind in case implementation uncovers some divergence

**Comment by seanpk** [comment]
@dannylevenson the function you want from the `swagger` service is `validateObject`.
